### PR TITLE
Implement endpoint to withdraw a course that a user is enrolled in

### LINKED ISSUE #108: Endpoint to withdraw a course
**Describe the task that needs to be done.**
Create an API endpoint that withdraws a course that the user is enrolled in. 

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
API endpoint can successfully withdraw a course that the user is enrolled in and is no longer a student in that course.
**Notes**

### PR DESCRIPTION
**Pull request by R055A**
## Description

Solves Issue #108 

Implemented API endpoint that withdraws a course that a user is enrolled in. A user is unenrolled from a course while the course remains available for other currently enrolled users and for future enrolments. The unenrolled user is no longer a student in that course and the number of students is decremented for that course.

## How has this been tested?

Automated test cases have been added to test the successful removal of the same course for different users followed by the unsuccessful removal of the same course no longer enrolled in for each user.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by kimslor — COMMENTED** [review]
This looks pretty good. But lets wait for the CI fix PR to be merged so that we can be certain that this passes the CI.

**Review by NicholasBatesNZ — APPROVED** [review]
LGTM

**Comment by R055A** [comment]
> This looks pretty good. But lets wait for the CI fix PR to be merged so that we can be certain that this passes the CI.

Thank you! All tests pass locally. I will merge the CI fix PR now and we will see.

**Comment by R055A** [comment]
> > This looks pretty good. But lets wait for the CI fix PR to be merged so that we can be certain that this passes the CI.
> 
> Thank you! All tests pass locally. I will merge the CI fix PR now and we will see.

It turns out that without new changes to this PR the now merged workflow for this repository will not be executed.

You could instead run the tests locally if you haven't already and let me know how it goes for you @kimslor

**Comment by kimslor** [comment]
I've tested it locally and it has passed. So feel free to merge it in. @R055A

**Review by kimslor — APPROVED** [review]

**Review by AlexMiao7 — APPROVED** [review]

**Comment by R055A** [comment]
> LGTM

I just noticed you have been included in the pull request review. Sorry, but thanks for the review!

**Pull request merged**
