### PR TITLE
Implementing Socket I/O Library

### LINKED ISSUE #38: Setting up Socket I/O library in Java
**Describe the task that needs to be done.**

Set up Socket I/O library to use for continuous communication between users.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**

There would be a Socket I/O library in the project for creating events for communication

**Notes**

As discussed in Communications meeting.

### PR DESCRIPTION
**Pull request by ejstuart**
## Description
*Please include a summary of the change and which issue number is fixed (e.g. Fixes #1). Please also include relevant motivation and context.*
Setup Socket I/O Library in java along with a basic chat handler to check that information can be sent to the backed. Uses this Socket I/O library: https://github.com/mrniko/netty-socketio

This is a very basic implementation that is liable to change as is needed.

Fixes #38 

## How has this been tested?
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.*

- Ran the ChatHandler class as main and open up this html file: 
https://github.com/mrniko/netty-socketio-demo/blob/master/client/namespace-index.html

## Screenshots
*Provide screenshots of what has been implemented. Leave blank if not applicable*

## Checklist
*(Leave blank if not applicable)*

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by scorpionknifes — COMMENTED** [review]
Hey, just a reminder to branch off from your fork (e.g branch off ejstuart:main)

Bit confused about your folder structure? is there any reason why it is so deep?
Flynn recommends: socket/ChatEventHandler.java

**Comment by dogeliness** [comment]
> Hey, just a reminder to branch off from your fork (e.g branch off ejstuart:main)
> 
> Bit confused about your folder structure? is there any reason why it is so deep? Flynn recommends: socket/ChatEventHandler.java

Possibly useful if there are future classes to add under socket but not socket io :thinking:

**Review by dogeliness — APPROVED** [review]
See comment above if you want to change it, otherwise is good start

**Comment by ejstuart** [comment]
> Hey, just a reminder to branch off from your fork (e.g branch off ejstuart:main)
> 
> Bit confused about your folder structure? is there any reason why it is so deep? Flynn recommends: socket/ChatEventHandler.java

Sorry about the branch thing, thanks for the reminder.
Folder structure is pretty much just because I was messing around with a few different implementations and libraries before deciding on this and just forgot to change it to something simpler, my bad. I'll make those changes now

**Pull request closed without merging**
