### PR TITLE
Fix for 401s when trying to access the API

### PR DESCRIPTION
**Pull request by JafarMaash**
Disabled security autoconfiguration

## Description
*Please include a summary of the change and which issue number is fixed (e.g. Fixes #1). Please also include relevant motivation and context.*
This is to fix the issue of getting 401s when trying to access the API due to Spring's security autoconfiguration. 
Reference article:
https://www.yawintutor.com/using-generated-security-password-spring-boot/#:~:text=The%20log%20%E2%80%9CUsing%20generated%20security,removed%20or%20customized%20using%20configurations.

## How has this been tested?
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.*
Added the fix and then ran the application and hit the basic hello world endpoint. It worked immediately without 401. 

## Screenshots
*Provide screenshots of what has been implemented. Leave blank if not applicable*

## Checklist
*(Leave blank if not applicable)*

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by ff-dev-45 — CHANGES_REQUESTED** [review]
Looking great, just so that we can check if all the tests pass, are you able to wait for this pr #89 to go through and then rebase your branch, after that we can see if the build/test passed

**Comment by JafarMaash** [comment]
> Looking great, just so that we can check if all the tests pass, are you able to wait for this pr #89 to go through and then rebase your branch, after that we can see if the build/test passed

No worries, just ping me once it's merged and I can do that

**Comment by ff-dev-45** [comment]
@JafarMaash merge just gone through, so you should be good to rebase and push the change

**Review by ff-dev-45 — APPROVED** [review]
LGTM, we will fix actions later

**Comment by JafarMaash** [comment]
Fix done in #93

**Pull request closed without merging**
